spring:
  application:
    name: quantum-safe-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/quantum_safe_transfer
    username: postgres
    password: 2375
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "WIcaM2ThKPgBNzrJw2KHqxNxnVwCnGozKwgQPW5JQehmHmLPY5+s3tEWpazZD0SFE9XmJ/sc6N1aJenulUJ9eQ=="
  access-token-expiration: 900000
  refresh-token-expiration: 604800000